Merge GFDL new dynamic core
NOAA-EMC/GFDL_atmos_cubed_sphere pull request #15
Opened 2020-02-13 19:58 UTC by XiaqiongZhou-NOAA

To merge GFDL new dynamic core 201912 release version to EMC

Related pull requests:

2020-02-13 20:50 UTC, climbfuji reviewed
I checked the code changes from a CCPP perspective only. There are some small changes for the saturation adjustment where I am wondering if we need to make corresponding changes in CCPP, for example the change in index ranges for delz. Have you run regression tests with and without CCPP to see if you get b4b identical results (need to do in REPRO mode)?

EDIT: I see that the fv3atm PR points to your version of ccpp-physics. I didn't see the PR, but I assume it is still coming. If so, then please consider my question as answered. Thanks!

EDIT 2: It just showed up - https://github.com/NCAR/ccpp-physics/pull/397. Thanks very much.

2020-02-13 21:24 UTC, XiaqiongZhou-NOAA commented
Dom:
I did the regression tests with/without CCPP. The results are b2b identical, except the nesting and regional tests (they are supposed to be different).

2020-02-13 21:36 UTC, climbfuji commented
This is awesome, thanks very much for making the ccpp-physics changes. I am fine with all of your changes and will approve/merge the ccpp-physics PR in coordination with the other repositories.

2020-02-18 18:09 UTC, bensonr commented
@climbfuji @junwang-noaa @DusanJovic-NOAA Please be aware this update requires a specific minimum version of FMS (2020.02) that has not yet been released.  Current schedules have this release hitting towards the end of March.

2020-02-21 16:48 UTC, jswhit2 commented
Is there some documentation on the dycore updates?  Looks like virtually every line of code changed, so it will be very difficult to review this by looking at the diffs.

2020-02-21 17:39 UTC, bensonr commented
@jswhit2 Please see the release notes in the authoritative repository: https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/master/RELEASE.md

2020-02-21 20:04 UTC, HenryJuang-NOAA commented
Don't know why my account in GitHut points to my personal email.
BTW, is it including multi_gases?

XiaqiongZhou-NOAA <notifications@github.com> 於 2020年2月13日 週四 下午4:09寫道：

> @XiaqiongZhou-NOAA <https://github.com/XiaqiongZhou-NOAA> requested your
> review on: #15
> <https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/15> Merge GFDL
> new dynamic core to EMC fork/branch.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/15?email_source=notifications&email_token=ALRWWEN7MIFKD2WT4B7XVLDRCWZGVA5CNFSM4KUZZYTKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOWT6466I#event-3036532601>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALRWWELW7RFZ7KT4IZUUXY3RCWZGVANCNFSM4KUZZYTA>
> .
>

2020-02-21 20:19 UTC, XiaqiongZhou-NOAA commented
@HenryJuang-NOAA 
The base repository is the EMC version with the commit a56907a44461c7151e0ba266e160c8f1a1685882 (Jan 6. 2020). The multi-gases included, but since the code changed a lot, please check if the multi-gases part is all right.

2020-02-21 20:26 UTC, HenryJuang-NOAA commented
I found multi_gases portion, I will review those.

莊漢明 <henry.juang@g.ncu.edu.tw> 於 2020年2月21日 週五 下午3:04寫道：

> Don't know why my account in GitHut points to my personal email.
> BTW, is it including multi_gases?
>
> XiaqiongZhou-NOAA <notifications@github.com> 於 2020年2月13日 週四 下午4:09寫道：
>
>> @XiaqiongZhou-NOAA <https://github.com/XiaqiongZhou-NOAA> requested your
>> review on: #15
>> <https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/15> Merge GFDL
>> new dynamic core to EMC fork/branch.
>>
>> —
>> You are receiving this because your review was requested.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/15?email_source=notifications&email_token=ALRWWEN7MIFKD2WT4B7XVLDRCWZGVA5CNFSM4KUZZYTKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOWT6466I#event-3036532601>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ALRWWELW7RFZ7KT4IZUUXY3RCWZGVANCNFSM4KUZZYTA>
>> .
>>
>

2020-02-22 03:38 UTC, HenryJuang-NOAA requested changes
tools/fv_treat_da_inc.F90 LINE 292, needs "," between q(:,:,:,spfo3) and is_in.

2020-02-24 18:43 UTC, jswhit2 commented
@pjpegion - you might want to make sure the IAU and stochastic physics stuff is still working.

2020-02-24 20:46 UTC, pjpegion commented
@jswhit2 I haven't run any tests yet, but the stochastic and iau code looks to be ok.

2020-03-04 19:06 UTC, XiaqiongZhou-NOAA commented
@HenryJuang-NOAA 
tools/fv_diagnostic line 6205-6360 are new. Could you check how to add the multi-gases option there especially the subroutine sounding_column? "qsmith" is not working since it needs more input variables with multi_gases is on.

2020-03-04 19:15 UTC, HenryJuang-NOAA commented
give me the link of the code, I am not so familiar to find your code to
locate 6205. For code I have, less than 6205 for fv_diagnostics.F90

XiaqiongZhou-NOAA <notifications@github.com> 於 2020年3月4日 週三 下午2:06寫道：

> @HenryJuang-NOAA <https://github.com/HenryJuang-NOAA>
> tools/fv_diagnostic line 6205-6360 are new. Could you check how to add the
> multi-gases option there especially the subroutine sounding_column?
> "qsmith" is not working since it needs more input variables with
> multi_gases is on.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/15?email_source=notifications&email_token=ALRWWEKIFR5QJ6JJTL5SHWLRF2RDLA5CNFSM4KUZZYTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENZUZ2Y#issuecomment-594758891>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALRWWEKECWE3AMK6LVFHPQ3RF2RDLANCNFSM4KUZZYTA>
> .
>

2020-03-04 19:26 UTC, XiaqiongZhou-NOAA commented
@HenryJuang-NOAA 
https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/15/files#diff-4d77029da1967b051ed6e46d5b31fde6
You can load diff for tools/fv_diagnostics.F90 to compare the old version and new version.

or check  my github repository https://github.com/XiaqiongZhou-NOAA/GFDL_atmos_cubed_sphere

2020-03-04 21:16 UTC, HenryJuang-NOAA commented
Got it!
You need to add #ifdef MULTI_GASES to include use of multi_gases_mod and
have ncnst or up to num_gas. For qsmith, you have to check other place
using qsmith with MULTI_GASES.
How can I add code into your branch? or how can I help you to add
MULTI_GASES into the new place for you to test?


XiaqiongZhou-NOAA <notifications@github.com> 於 2020年3月4日 週三 下午2:26寫道：

> @HenryJuang-NOAA <https://github.com/HenryJuang-NOAA>
>
> https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/15/files#diff-4d77029da1967b051ed6e46d5b31fde6
> You can load diff for tools/fv_diagnostics.F90 to compare the old version
> and new version.
>
> or check my github repository
> https://github.com/XiaqiongZhou-NOAA/GFDL_atmos_cubed_sphere
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/15?email_source=notifications&email_token=ALRWWEIK5JNLNTHKCG55QO3RF2TO5A5CNFSM4KUZZYTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENZYZ5I#issuecomment-594775285>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALRWWEJMP3E2F2FKY33IAB3RF2TO5ANCNFSM4KUZZYTA>
> .
>

2020-05-13 15:14 UTC, climbfuji reviewed
Holy cow, quite a number of changes. Looks ok to my limited understanding of the dycore. I was looking specifically for changes with impact on the CCPP. I left a comment on the MULTI_GASES option and a few requests for cosmetic changes.

2020-05-13 15:14 UTC, climbfuji commented on driver/fvGFS/atmosphere.F90
> +!                    mpp_npes, mpp_pe, mpp_chksum,mpp_get_current_pelist,
Would you mind removing the trailing whitespaces that are added by this commit?

2020-05-13 15:14 UTC, climbfuji commented on driver/fvGFS/atmosphere.F90
> +!LMH 28sep18: If the name of a tracer ends in 'nopbl' then do NOT update it;
I wonder if this feature is/will be used by the UFS and if this is documented somewhere.

2020-05-13 15:14 UTC, climbfuji commented on model/fv_control.F90
>  #ifdef MULTI_GASES
Since we do not have regression tests with MULTI_GASES turned on, has someone tested this feature manually. In particular of the CCPP version works as expected?

2020-05-13 15:14 UTC, climbfuji commented on model/fv_control.F90
>  #ifdef MULTI_GASES
@HenryJuang-NOAA

2020-05-13 15:14 UTC, climbfuji commented on model/fv_nesting.F90
> +
I would remove the extra whitespaces in lines 215, 218, 227.

2020-05-13 20:06 UTC, TomBlack-NOAA approved these changes

2020-05-14 13:47 UTC, XiaqiongZhou-NOAA commented on model/fv_control.F90
>  #ifdef MULTI_GASES
Multi_GASES was tested for this version with 64-bits.
Another pull requests is generated to the regression test  https://github.com/ufs-community/ufs-weather-model/pull/112. Some fixes are needed for 32-bits runs in that pull request.

2020-05-14 15:04 UTC, bensonr requested changes
Please see the inlined comments regarding multi-gases namelist reads.

2020-05-14 15:04 UTC, bensonr commented on model/fv_control.F90
> +#endif
This new version of fv_control has each namelist read contained within its own programmatic unit.  Please create a separate subroutine for the multi-gases nml read and add a #ifdef gated call in the proper place.

2020-05-14 15:04 UTC, bensonr commented on model/fv_control.F90
>  #endif
See comment above regarding separate programmatic unit for multi-gases nml.

2020-05-14 15:33 UTC, HenryJuang-NOAA commented
There are many *_nml included in input.nml, so all *_nml use the same unit
number through input.nml. I don't see any reason to have one of them doing
something different from others....

On Thu, May 14, 2020 at 11:04 AM bensonr <notifications@github.com> wrote:

> *@bensonr* requested changes on this pull request.
>
> Please see the inlined comments regarding multi-gases namelist reads.
> ------------------------------
>
> In model/fv_control.F90
> <https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/15#discussion_r425190913>
> :
>
> > +#ifdef MULTI_GASES
> +   namelist /multi_gases_nml/ rilist,cpilist
> +#endif
>
> This new version of fv_control has each namelist read contained within its
> own programmatic unit. Please create a separate subroutine for the
> multi-gases nml read and add a #ifdef gated call in the proper place.
> ------------------------------
>
> In model/fv_control.F90
> <https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/15#discussion_r425194247>
> :
>
> > @@ -738,26 +1067,12 @@ subroutine run_setup(Atm, dt_atmos, grids_on_this_pe, p_split)
>        read (input_nml_file,multi_gases_nml,iostat=ios)
>        ierr = check_nml_error(ios,'multi_gases_nml')
>  #endif
>
> See comment above regarding separate programmatic unit for multi-gases nml.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/15#pullrequestreview-411875344>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALRWWEPDW5R6RXTNCCPVQLDRRQB7RANCNFSM4KUZZYTA>
> .
>

2020-05-14 15:38 UTC, HenryJuang-NOAA commented
I see, sorry! Each one has its own unit.
Well! What is the good reason to have each nml have its own unit?


On Thu, May 14, 2020 at 11:04 AM bensonr <notifications@github.com> wrote:

> *@bensonr* requested changes on this pull request.
>
> Please see the inlined comments regarding multi-gases namelist reads.
> ------------------------------
>
> In model/fv_control.F90
> <https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/15#discussion_r425190913>
> :
>
> > +#ifdef MULTI_GASES
> +   namelist /multi_gases_nml/ rilist,cpilist
> +#endif
>
> This new version of fv_control has each namelist read contained within its
> own programmatic unit. Please create a separate subroutine for the
> multi-gases nml read and add a #ifdef gated call in the proper place.
> ------------------------------
>
> In model/fv_control.F90
> <https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/15#discussion_r425194247>
> :
>
> > @@ -738,26 +1067,12 @@ subroutine run_setup(Atm, dt_atmos, grids_on_this_pe, p_split)
>        read (input_nml_file,multi_gases_nml,iostat=ios)
>        ierr = check_nml_error(ios,'multi_gases_nml')
>  #endif
>
> See comment above regarding separate programmatic unit for multi-gases nml.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/15#pullrequestreview-411875344>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALRWWEPDW5R6RXTNCCPVQLDRRQB7RANCNFSM4KUZZYTA>
> .
>

2020-05-14 16:00 UTC, bensonr commented
@HenryJuang-NOAA The comment is not referring to a file unit, but a programmatic unit - i.e. subroutine.  Each namelist read in the updated code base is now encapsulated within a separate subroutine.  If the multi-gases namelist logic is encapsulated within a separate, dedicated subroutine, it will remove many MULTI_GASES #ifdef-#endif pairs as the subroutine would not need any.  In fact, now that I look more closely at the codebase itself, all of the namelist logic regarding multi-gases should be encapsulated within the multi-gases_Init within the multi_gases.F90 source file.

2020-05-14 16:07 UTC, XiaqiongZhou-NOAA commented on model/fv_control.F90
> +#endif
Can this be changed in the next pull request when we add the regression test for MULTI_GASES?

2020-05-14 17:04 UTC, bensonr commented
Sure.  As mentioned in a later comment, this logic should all be moved to
the multi_gases_init routine in multi_gases.F90 and the call to
multi_gases_init should be moved to the same level as the calls to the
individual namelist reads.

2020-05-14 17:12 UTC, HenryJuang-NOAA commented
In fact, I like all nml in one place instead of spreading around different
subroutines.... it is easily to find one place for all nml lists instead of
all places for one function for nml.... especially, we all are used to the
original way, why keep changing.......?????

ifdef multi-gases is an option, but it can be in as default, then all ifdef
can be removed later... I don't worry too much of ifdef... many options
around in the code, I have already used to them... good thing for itdef is
that it saves running time if statement and very easy to insert and remove
from code...

On Thu, May 14, 2020 at 12:00 PM bensonr <notifications@github.com> wrote:

> @HenryJuang-NOAA <https://github.com/HenryJuang-NOAA> The comment is not
> referring to a file unit, but a programmatic unit - i.e. subroutine. Each
> namelist read in the updated code base is now encapsulated within a
> separate subroutine. If the multi-gases namelist logic is encapsulated
> within a separate, dedicated subroutine, it will remove many MULTI_GASES
> #ifdef-#endif pairs as the subroutine would not need any. In fact, now that
> I look more closely at the codebase itself, all of the namelist logic
> regarding multi-gases should be encapsulated within the multi-gases_Init
> within the multi_gases.F90 source file.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/15#issuecomment-628730021>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALRWWEI7T3NLN2DSR3JKLNLRRQISNANCNFSM4KUZZYTA>
> .
>

2020-05-14 17:15 UTC, HenryJuang-NOAA commented
multi-gases originally is for WAM, and you already put it with WAM in RT.
If you want to create a new RT for regular gfs in next pull, it is fine to
me. It should be better with gfs RT.

On Thu, May 14, 2020 at 12:08 PM XiaqiongZhou-NOAA <notifications@github.com>
wrote:

> *@XiaqiongZhou-NOAA* commented on this pull request.
> ------------------------------
>
> In model/fv_control.F90
> <https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/15#discussion_r425255717>
> :
>
> > +#ifdef MULTI_GASES
> +   namelist /multi_gases_nml/ rilist,cpilist
> +#endif
>
> Can this be changed in the next pull request when we add the regression
> test for MULTI_GASES?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/15#discussion_r425255717>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALRWWELGB6V74FDDINWWHADRRQJN5ANCNFSM4KUZZYTA>
> .
>

2020-05-15 12:54 UTC, XiaqiongZhou-NOAA commented on driver/fvGFS/atmosphere.F90
> +!LMH 28sep18: If the name of a tracer ends in 'nopbl' then do NOT update it;
This is the part added when merge  the master branch of GFDL dycore.  Lucas could know it better.

2020-05-15 13:01 UTC, XiaqiongZhou-NOAA commented on driver/fvGFS/atmosphere.F90
> +!                    mpp_npes, mpp_pe, mpp_chksum,mpp_get_current_pelist,
Dom:
Is this the only place to revise about the trailing whitespaces?
I noticed that there are many "^M" hiding in the file fv_regional_bc.F90 at the end of each line. Is it matter?

2020-05-15 13:05 UTC, XiaqiongZhou-NOAA commented on driver/fvGFS/atmosphere.F90
> +!                    mpp_npes, mpp_pe, mpp_chksum,mpp_get_current_pelist,
^M will be removed.

2020-06-09 13:43 UTC, climbfuji approved these changes
I did review this PR a few weeks ago, not much has changed since then. I mainly focussed on changes around the CCPP fast physics blocks, looks good to me.

2020-06-09 13:43 UTC, climbfuji commented on tools/sorted_index.F90
> +!* useful, but WITHOUT ANYWARRANTY; without even the implied warranty
typo: ANYWARRANTY -> ANY WARRANTY

2020-06-09 14:49 UTC, TomBlack-NOAA approved these changes
Regional module changes in particular appear to be okay.

2020-06-09 14:51 UTC, TomBlack-NOAA approved these changes

2020-06-09 16:48 UTC, HenryJuang-NOAA approved these changes

2020-06-09 17:00 UTC, junwang-noaa approved these changes

2020-06-09 21:30 UTC, merged