Regional BC blending and BCs into GSI
NOAA-EMC/GFDL_atmos_cubed_sphere pull request #16
Opened 2020-03-12 15:39 UTC by TomBlack-NOAA

2020-04-03 13:14 UTC, junwang-noaa commented on driver/fvGFS/atmosphere.F90
> +        if(Atm(n)%pt(i,j,k)>400.)then
This can be added later, but If we have bad Temperature >400, can we stop model from continue running?

2020-04-03 13:25 UTC, junwang-noaa commented on model/fv_regional_bc.F90
> +   write(0,*)' enter setup_regional_BC isd=',isd,' ied=',ied,' jsd=',jsd,' jed=',jed
We may want to comment this line or make it option whether to print out this line? This could be part of the job error file clean up work.

2020-04-03 13:27 UTC, TomBlack-NOAA commented
Jun,

That block is probably left over from debugging that I missed removing 
so it's fine to take it out.

Tom

On 4/3/2020 9:15 AM, Jun Wang wrote:
>
> *@junwang-noaa* commented on this pull request.
>
> ------------------------------------------------------------------------
>
> In driver/fvGFS/atmosphere.F90 
> <https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/16#discussion_r402996099>:
>
> > @@ -1630,6 +1630,18 @@ subroutine atmosphere_state_update (Time, IPD_Data, IAU_Data, Atm_block, flip_vc
>   
>        call nullify_domain()
>        call timing_on('FV_DIAG')
> +
> +      do k=1, Atm(n)%npz
> +      do j=lbound(Atm(n)%pt,2),ubound(Atm(n)%pt,2)
> +      do i=lbound(Atm(n)%pt,1),ubound(Atm(n)%pt,1)
> +        if(Atm(n)%pt(i,j,k)>400.)then
>
> This can be added later, but If we have bad Temperature >400, can we 
> stop model from continue running?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/16#pullrequestreview-387243525>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ALQGGOZOMHRT4FRQRG6ZZJTRKXONZANCNFSM4LGPBKUQ>.
>

2020-04-03 13:29 UTC, TomBlack-NOAA commented
Jun,

We would at least need the option to print those values.  They can be 
very valuable when debugging and when adding/modifying the code.

Tom

On 4/3/2020 9:25 AM, Jun Wang wrote:
>
> *@junwang-noaa* commented on this pull request.
>
> ------------------------------------------------------------------------
>
> In model/fv_regional_bc.F90 
> <https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/16#discussion_r403002890>:
>
> > @@ -260,6 +311,7 @@ subroutine setup_regional_BC(Atm                                  &
>         east_bc =.false.
>         west_bc =.false.
>   !
> +   write(0,*)' enter setup_regional_BC isd=',isd,' ied=',ied,' jsd=',jsd,' jed=',jed
>
> We may want to comment this line or make it option whether to print 
> out this line? This could be part of the job error file clean up work.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/16#pullrequestreview-387252365>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ALQGGO6V7J2VBSP7MNNOYHTRKXPVPANCNFSM4LGPBKUQ>.
>

2020-04-03 16:00 UTC, bensonr requested changes
Are the *_65lyrs and *_NAM_lyrs files test files from previous work?  If so, please delete them from the merge.  If they are necessary, please document the need for them.

2020-04-03 16:00 UTC, bensonr commented on driver/fvGFS/atmosphere.F90
> +        if(Atm(n)%pt(i,j,k)>400.)then
If you turn on the namelist "range_warn" the call to fv_diag will check the temperature for the data domain.  An FMS "NOTE" will be emitted for temperatures outside the range of (150 - 350).

2020-04-03 16:00 UTC, bensonr commented on model/fv_regional_bc.F90
> +!* or see:   http://www.gnu.org/licenses/gpl.html                      *
This license header is outdated.  The one being replaced is the correct version.  Please fix and push a new udpate for this file.

2020-04-03 16:00 UTC, bensonr commented on model/fv_regional_bc.F90
> +        call abort()
Please consider using the FMS error_msg function which when given the FATAL parameter will write an error message to the screen and abort gracefully.

2020-04-03 16:00 UTC, bensonr commented on model/fv_regional_bc.F90
> +          regional_bc_bounds%je_east_uvs=jed-nhalo_model+1
All other uses of nhalo_model have been modified to include nrows_blend in some fashion.  Should this one be modified in a similar fashion?

2020-04-03 16:00 UTC, bensonr commented on model/fv_regional_bc.F90
> +      write(0,*)' opened grid file ',trim(filename)
Please consider using the standard FMS error_msg function with the NOTE parameter for output of this nature.

2020-04-03 16:00 UTC, bensonr commented on model/fv_regional_bc.F90
> +        call abort()
Please consider using the FMS error_msg function with the FATAL parameter to output a message and cleanly abort the model.

2020-04-03 16:00 UTC, bensonr commented on model/fv_regional_bc.F90
> +66811 format(' allocated delp_BC(',i3,':',i3,',',i3,':',i3,')')
Is this a debug message that is no longer needed?

2020-04-03 16:00 UTC, bensonr commented on model/fv_regional_bc.F90
> +            call abort()
Please consider using FMS error_msg with the FATAL parameter to output the message and cleanly abort the model.

2020-04-03 16:00 UTC, bensonr commented on tools/external_ic.F90
> +!         endif
Do these lines need to be kept for documentation purposes or can they be removed?

2020-04-03 16:00 UTC, bensonr commented on tools/fv_eta.F90
> +!                1.0000000000e+00 /
Should there be an #ifdef/#else/#endif around this and the NAM level definition below to make it easier to switch back and forth between the two definitions for 60 levels?

2020-04-03 16:00 UTC, bensonr commented on tools/fv_eta.F90
> +          ks = 19
Same as the comment above regarding #ifdef.

2020-04-03 17:41 UTC, TomBlack-NOAA commented on driver/fvGFS/atmosphere.F90
> +        if(Atm(n)%pt(i,j,k)>400.)then
Let's remove this block since I'm sure I put it there for debugging.

2020-04-03 17:43 UTC, TomBlack-NOAA commented on model/fv_regional_bc.F90
> +   write(0,*)' enter setup_regional_BC isd=',isd,' ied=',ied,' jsd=',jsd,' jed=',jed
Let's just comment out the line.  I know it's very valuable for dealing with some MPI-related problems so it's nice to have it sitting there.

2020-04-03 17:44 UTC, TomBlack-NOAA commented on model/fv_regional_bc.F90
> +!* or see:   http://www.gnu.org/licenses/gpl.html                      *
I'll replace this with the new header.

2020-04-03 17:59 UTC, TomBlack-NOAA commented on model/fv_regional_bc.F90
> +        call abort()
Will replace with call to mpp_error.

2020-04-03 18:09 UTC, TomBlack-NOAA commented on model/fv_regional_bc.F90
> +          regional_bc_bounds%je_east_uvs=jed-nhalo_model+1
This is okay.  It is on the east side so the I index must include blending rows extending into the integration domain.  Blending on the east side (and west side) is irrelevant to the J dimension.

2020-04-03 18:13 UTC, TomBlack-NOAA commented on model/fv_regional_bc.F90
> +66811 format(' allocated delp_BC(',i3,':',i3,',',i3,':',i3,')')
Most likely.  I'll remove it.

2020-04-03 18:14 UTC, TomBlack-NOAA commented on tools/external_ic.F90
> +!         endif
I think they can be removed.

2020-04-03 18:16 UTC, TomBlack-NOAA commented on tools/fv_eta.F90
> +!                1.0000000000e+00 /
I believe these should be removed.

2020-04-03 18:16 UTC, TomBlack-NOAA commented on tools/fv_eta.F90
> +          ks = 19
Likewise, let's remove it.

2020-04-03 20:27 UTC, TomBlack-NOAA commented on model/fv_regional_bc.F90
> +            call abort()
Will replace with mpp_error.

2020-04-06 17:53 UTC, junwang-noaa approved these changes

2020-04-07 14:15 UTC, bensonr approved these changes
I approve the changes.

2020-04-08 13:33 UTC, merged